apiVersion: apps/v1
kind: Deployment
metadata:
  name: material
  labels:
    app: material
spec:
  replicas: 1
  selector:
    matchLabels:
      app: material
  template:
    metadata:
      labels:
        app: material
    spec:
      containers:
        - name: material
          image: "username/material:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
