server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: material
          uri: http://localhost:8082
          predicates:
            - Path=/materials/**, 
        - id: advertisement
          uri: http://localhost:8083
          predicates:
            - Path=/advertisements/**, 
        - id: inventory
          uri: http://localhost:8084
          predicates:
            - Path=/inventories/**, 
        - id: delivery
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**, 
        - id: ad status
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: material
          uri: http://material:8080
          predicates:
            - Path=/materials/**, 
        - id: advertisement
          uri: http://advertisement:8080
          predicates:
            - Path=/advertisements/**, 
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: ad status
          uri: http://adStatus:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
