apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad_status
  labels:
    app: ad_status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad_status
  template:
    metadata:
      labels:
        app: ad_status
    spec:
      containers:
        - name: ad_status
          image: "user02.azurecr.io/ad_status:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
